name: Link Issues in PR

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  link-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Link Issue in PR Description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract the issue number from the branch name
          ISSUE_NUMBER=$(echo "${{ github.head_ref }}" | grep -oE 'issue-[0-9]+' | cut -d '-' -f2)
          if [ ! -z "$ISSUE_NUMBER" ]; then
            # Fetch the current PR description
            PR_DESCRIPTION=$(gh pr view ${{ github.event.pull_request.number }} --json body -q ".body")

            # Fetch the title of the issue using GitHub CLI
            ISSUE_TITLE=$(gh issue view $ISSUE_NUMBER --json title -q ".title")

            # Create the issue link
            ISSUE_LINK="https://github.com/${{ github.repository }}/issues/$ISSUE_NUMBER"
            LINK_TEXT="Linked Issue: [$ISSUE_TITLE]($ISSUE_LINK)"
            FIX_TEXT="Fixes #$ISSUE_NUMBER"

            # Check if the link already exists in the PR description to prevent duplication
            if [[ "$PR_DESCRIPTION" != *"$LINK_TEXT"* ]]; then
              UPDATED_DESCRIPTION="${PR_DESCRIPTION}"$'\n\n'"$LINK_TEXT"$'\n'$FIX_TEXT

              # Update the PR description using echo to handle new lines properly
              echo "$UPDATED_DESCRIPTION" | gh pr edit ${{ github.event.pull_request.number }} --body-file -
            fi
          fi
